"""
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, 
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Assignment: By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
Answer: 4613732
"""

def evenFibs():
    sum = 0
    fibList = [1, 2]
    while fibList[-1] < 4000000:
        if (fibList[-1] % 2) == 0: sum += fibList[-1]
        fibList.append(fibList[-1] + fibList[-2])
    return sum

print evenFibs()